# Generated by Django 4.2.1 on 2023-06-21 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_project_user_project_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='joined_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
