# Generated by Django 4.2.1 on 2023-06-23 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_project_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(choices=[('read', 'Read'), ('add_users', 'Add Users'), ('create_tasks', 'Create Tasks'), ('modify_tasks', 'Modify Tasks'), ('delete_tasks', 'Delete Tasks'), ('modify_other_users_permissions', 'Modify Other Users Permissions'), ('delete_users', 'Delete Users'), ('delete_project', 'Delete Project')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
