# Generated by Django 4.2.1 on 2023-06-23 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_projectmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read'), ('add_users', 'Add Users'), ('create_tasks', 'Create Tasks'), ('modify_tasks', 'Modify Tasks'), ('delete_tasks', 'Delete Tasks'), ('modify_other_users_permissions', 'Modify Other Users Permissions'), ('delete_users', 'Delete Users'), ('delete_project', 'Delete Project')], max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='ProjectMembership',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='joined_projects', through='core.ProjectPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
