# Generated by Django 4.2.1 on 2023-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_projectpermission_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
