# Generated by Django 4.2.1 on 2023-06-24 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_projectpermission_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('add_users', 'Add Users'), ('create_tasks', 'Create Tasks'), ('modify_tasks', 'Modify Tasks'), ('delete_tasks', 'Delete Tasks'), ('modify_other_users_permissions', 'Modify Other Users Permissions'), ('delete_users', 'Delete Users'), ('delete_project', 'Delete Project'), ('creator', 'Creator')], max_length=30),
        ),
    ]
